name: build+deploy

on:
  push:
    branches:
    - main

jobs:
  main:
    env:
      SERVER_IP: ${{ secrets.SERVER_IP }}
      SERVER_KEYSCAN: ${{ secrets.SERVER_KEYSCAN }}
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: install node
      uses: actions/setup-node@v1
      with:
        node-version: '17.x'
    - name: install dependencies
      run: yarn install --frozen-lockfile
    - name: test
      run: yarn jest
    - name: create env file
      env:
        ENV: ${{ secrets.ENV }}
      run: echo "$ENV" > .env
    - name: extract resources
      env:
        ENCRYPTION_PASSWORD: ${{ secrets.ENCRYPTION_PASSWORD }}
      run: echo "$ENCRYPTION_PASSWORD" | gpg --batch --quiet --passphrase-fd 0 -d resources.tar.gz.gpg | tar -xz
    - name: verify all resources
      run: yarn ts-node source/temp.ts
    - name: build & bundle
      run: yarn build
    - name: build docker image
      run: docker build . --file Dockerfile --tag inscryption-card-generator:ci
    
    - name: run docker image
      run: docker run --rm -d -p 8080:8080 inscryption-card-generator:ci
    - name: wait for server to start (guess)
      run: sleep 10
    - name: validate server running
      run: if [ $(curl -s -o /dev/null -w '%{http_code}' localhost:8080) != 200 ]; then exit 1; fi
    - name: check generate act 1 card
      run: if [ $(curl -s -o /dev/null -w '%{http_code}' -d '{}' -X POST localhost:8080/api/card/leshy/) != 201 ]; then exit 1; fi
    - name: check generate act 2 card
      run: if [ $(curl -s -o /dev/null -w '%{http_code}' -d '{}' -X POST localhost:8080/api/card/gbc/) != 201 ]; then exit 1; fi
    - name: check generate pixel profilgate card
      run: if [ $(curl -s -o /dev/null -w '%{http_code}' -d '{}' -X POST localhost:8080/api/card/pixelprofilgate/) != 201 ]; then exit 1; fi
    - name: stop all container
      run: docker stop $(docker ps -a -q)
    - name: export docker image
      run: docker save inscryption-card-generator > inscryption-card-generator.tar
    - name: compress image
      run: gzip inscryption-card-generator.tar

    - name: init ssh agent
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}
    - name: add server to known hosts
      run: echo "$SERVER_IP ssh-rsa $SERVER_KEYSCAN" >> ~/.ssh/known_hosts
    - name: upload artifact
      run: scp inscryption-card-generator.tar.gz "ci@$SERVER_IP:/home/ci/"
    - name: unzip artifact
      run: ssh ci@$SERVER_IP "cd /home/ci/ && gzip -fd inscryption-card-generator.tar.gz"
    - name: remove previous image
      run: |
        ssh ci@$SERVER_IP 'docker stop $(docker ps -q) || echo "No container running. Skipping..."'
        ssh ci@$SERVER_IP 'docker image rm inscryption-card-generator || echo "No previous image exists. Skipping..."'
    - name: import container and remove artifact
      run: ssh ci@$SERVER_IP "cd /home/ci/ && docker load -i inscryption-card-generator.tar && rm inscryption-card-generator.tar"
    - name: stop/run container & prune old images
      run: ssh ci@$SERVER_IP "docker stop $(docker ps -q); docker run --rm -d -p 8080:8080 inscryption-card-generator:ci; docker image prune -a"
