name: build+deploy

on:
  push:
    branches:
    - feature/ci

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - run: which gpg openssl
  build:
    runs-on: ubuntu-latest
    env:
      ENCRYPTION_PASSWORD: ${{ secrets.ENCRYPTION_PASSWORD }}
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: install node
      uses: actions/setup-node@v1
      with:
        node-version: '17.x'
    - name: install dependencies
      run: yarn install --frozen-lockfile
    - name: build & bundle
      run: yarn build
    - name: extract resources
      run: echo "$ENCRYPTION_PASSWORD" | gpg --batch --quiet --passphrase-fd 0 -d resources.tar.gz.gpg | tar -xzf
    - name: build docker image
      run: docker build . --file Dockerfile --tag inscryption-card-generator:ci
    - name: run docker image
      run: docker run --rm inscryption-card-generator:ci

# todo: for later
# - name: export docker image
#   run: docker save inscryption-card-generator > inscryption-card-generator.tar
# - name: compress image
#   run: gzip inscryption-card-generator.tar
#
# - name: decompress image
#   run: gzip -d inscryption-card-generator.tar.gz
# - name: load docker image
#   run: docker load -i inscryption-card-generator.tar
